#
name: asuswrt-merlin-ax86u-CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
#  workflow_dispatch:
#    inputs:
#      clean_cache:
#        description: 'Clear caches'
#        required: false
#        type: boolean

# push:
#   branches: 
#     - master
  # schedule:
  #   - cron: 0 20 * * *
#  release:
#    types: [published]

jobs:

  build_asuswrt_merlin:

    name: Build Asuswrt firmware

    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: master

      - name: Setting the Linux environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo dpkg --add-architecture i386
          #cat /etc/apt/sources.list
          # replace 'deb' with 'deb [arch=arm64]'
          sudo sed 's/^deb http/deb [arch=arm64] http/' -i '/etc/apt/sources.list'
          sudo tee -a /etc/apt/sources.list.d/i386.list > /dev/null <<EOT
          deb [arch=i386] http://security.ubuntu.com/ubuntu/ focal-security  main restricted universe multiverse
          deb [arch=i386]  http://archive.ubuntu.com/ubuntu/ focal           main restricted universe multiverse
          deb [arch=i386]  http://archive.ubuntu.com/ubuntu/ focal-updates   main restricted universe multiverse
          deb [arch=i386]  http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
          EOT
          # sudo dpkg-reconfigure dash
          sudo ln -sf /bin/bash /bin/sh #使用bash,默认dash环境
          sudo apt clean  # 清除旧缓存
          sudo apt update  # 加载新的focal源
          sudo apt -f install  # 修复依赖
          sudo apt-get install libtool-bin cmake libproxy-dev uuid-dev liblzo2-dev autoconf autoconf-archive \
          automake bash bison bzip2 diffutils file flex m4 g++ gawk groff-base libncurses5-dev libtool libslang2 \
          make patch perl pkg-config shtool subversion tar texinfo zlib1g zlib1g-dev gettext libexpat1-dev \
          libssl-dev cvs gperf unzip python libxml-parser-perl gcc-multilib libxml2-dev g++-multilib git \
          libncurses5 mtd-utils libncurses5-dev libvorbis-dev autopoint autogen automake-1.15 sed build-essential \
          intltool libglib2.0-dev xutils-dev lib32z1-dev lib32stdc++6 xsltproc gtk-doc-tools libelf1:i386 gengetopt

          # sudo apt install gconf-editor gitk 
          
          # 可用空间仅有31GB,编译需要约34-38GB空间
          sudo rm -rf /usr/share/dotnet
          # 可获得3GB空间
          #df -h
          sudo rm -rf /usr/local/lib/android
          # 可获得11GB空间
          #df -h
          sudo rm -rf /opt/ghc
          # 可获得0GB空间
          df -h
      - name: git clone source
        run: |
          git clone https://github.com/RMerl/am-toolchains
          #全部clone将出现空间不足错误 
          #git clone https://github.com/RMerl/asuswrt-merlin.ng
          mkdir amng-build
          #rsync -a --del asuswrt-merlin.ng/ amng-build
          git clone -b 3004.388 https://github.com/RMerl/asuswrt-merlin.ng ./amng-build
          ls -la am-toolchains/.
          ls -la amng-build/.
      - name: setup toolchain
        run: |      
          sudo rm -rf /opt/toolchains
          # RMerl已不再支持Broadcom HND ARM platform (RT-AC86U, GT-AC2900)
          #sudo ln -s ./am-toolchains/brcm-arm-hnd /opt/toolchains
          #echo "export LD_LIBRARY_PATH=\$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/lib" >> ./.profile
          #echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ./.profile
          #echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ./.profile
          #echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ./.profile
    
          # Broadcom HND AX ARM platform (RT-AX56U, RT-AX58U, RT-AX86U, RT-AX88U, GT-AX11000, RT-AX68U):
          sudo ln -s $PWD/am-toolchains/brcm-arm-hnd /opt/toolchains
          echo "export LD_LIBRARY_PATH=\$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/lib" >> ./.profile
          echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ./.profile
          echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ./.profile
          echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ./.profile
          #编译出现can not find Toolchain,将toolchains目录放在当前目录下的方式不行,在/opt/toolchains下找
          #sudo ln -s $PWD/am-toolchains/brcm-arm-hnd $PWD/toolchains
          #echo "export LD_LIBRARY_PATH=\$LD_LIBRARY:$PWD/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/lib" >> ./.profile
          #echo "export TOOLCHAIN_BASE=$PWD/toolchains" >> ./.profile
          #echo "PATH=\$PATH:$PWD/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ./.profile
          #echo "PATH=\$PATH:$PWD/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ./.profile
          
          source ./.profile
          #cat ./.profile
          echo "path=$PATH"
          echo "toolchain=$TOOLCHAIN_BASE"
          echo "ld_library=$LD_LIBRARY_PATH"
          df -h
          #du -h ./ --max-depth=3
          du -h /opt/toolchains. --max-depth=3
          #du -h ./amng-build/. --max-depth=3
          ls -la /opt/toolchains
      - name: Compile firmware
        run: |
          #cd ./amng-build/release/src-rt-5.02hnd
          #make rt-ac86u
          cd ./amng-build/release/src-rt-5.02L.07p2axhnd
          make rt-ax86u

          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          #cd ./amng-build/release/src-rt-5.02hnd/targets
          cd ./amng-build/release/src-rt-5.02L.07p2axhnd/targets
          du -h ./ --max-depth=3
          
          # mv -n sha256sums-ng.txt sha256sums-ng-$(date +%Y%m%d).txt
          cp -rf ./962118GW/*.w $HOME/artifact/firmware/
          #cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          #cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          #cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
      - name: Deliver buildinfo
        uses: actions/upload-artifact@main
        with:
          name: buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@main
        with:
          name: package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@main
        with:
          name: firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true  
